
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 2PpFx09DSY6LWjwLim-x-A
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      kafka-topics --bootstrap-server kafka:9092 \
        --create --if-not-exists \
        --topic order.created \
        --partitions 3 \
        --replication-factor 1
  db-user-service:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - db_user_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  db-order-service:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - db_order_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_user_data:
  db_order_data: